# Generated by Django 5.1.6 on 2025-05-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pt_backend", "0017_user_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
